random_seed: 0
vocab_size: 20000
state_size: 1024
down_proj_size: 512
sentence_size: 20
embedding_size: 100
use_external_embedding: True
embedding_name: "wordembeddings-dim100.word2vec"
batch_size: 64
num_iter: 100000
learning_rate: 0.001
validation_interval: 5000
validation_size: 5000
log_dir: "./logs"
eval_file: 'sentences.test'
