random_seed: 0
model: 'rnn'
nb_frames: 0  # 0 means taking all the frames for each document
vocab_size: 20000
state_size: 512
embedding_size: 100
context_size: 10
batch_size: 64
num_iter: 100000
learning_rate: 0.001
validation_interval: 5000
validation_size: 5000
log_dir: "./logs"
training_file: 'sct_train_framenet.txt'
eval_prefix: 'val'
use_binary_features: True
